version: '2.4'
services:
    rsu1:
        hostname: rsu1
        image: vanetza:test
        cap_add:
            - "NET_ADMIN"
        environment:
            - VANETZA_STATION_ID=1
            - VANETZA_STATION_TYPE=15
            - VANETZA_MAC_ADDRESS=6e:06:e0:03:00:01
            - VANETZA_INTERFACE=br0
            - START_EMBEDDED_MOSQUITTO=true
            - SUPPORT_MAC_BLOCKING=true
            - VANETZA_CAM_PERIODICITY=0
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.10
        sysctls:
            kernel.msgmax: 16384

    rsu2:
        hostname: rsu2
        image: vanetza:test
        cap_add:
            - "NET_ADMIN"
        environment:
            - VANETZA_STATION_ID=2
            - VANETZA_STATION_TYPE=15
            - VANETZA_MAC_ADDRESS=6e:06:e0:03:00:02
            - VANETZA_INTERFACE=br0
            - START_EMBEDDED_MOSQUITTO=true
            - SUPPORT_MAC_BLOCKING=true
            - VANETZA_CAM_PERIODICITY=0
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.11
        sysctls:
            kernel.msgmax: 16384

    obu1:
        hostname: obu1
        image: vanetza:test
        cap_add:
            - "NET_ADMIN"
        environment:
            - VANETZA_STATION_ID=3
            - VANETZA_STATION_TYPE=5
            - VANETZA_MAC_ADDRESS=6e:06:e0:03:00:03
            - VANETZA_INTERFACE=br0
            - START_EMBEDDED_MOSQUITTO=true
            - SUPPORT_MAC_BLOCKING=true
            - VANETZA_CAM_PERIODICITY=0
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.20
        sysctls:
            kernel.msgmax: 16384

    obu2:
        hostname: obu2
        image: vanetza:test
        cap_add:
            - "NET_ADMIN"
        environment:
            - VANETZA_STATION_ID=4
            - VANETZA_STATION_TYPE=5
            - VANETZA_MAC_ADDRESS=6e:06:e0:03:00:04
            - VANETZA_INTERFACE=br0
            - START_EMBEDDED_MOSQUITTO=true
            - SUPPORT_MAC_BLOCKING=true
            - VANETZA_CAM_PERIODICITY=0
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.21
        sysctls:
            kernel.msgmax: 16384

    obu3:
        hostname: obu3
        image: vanetza:test
        cap_add:
            - "NET_ADMIN"
        environment:
            - VANETZA_STATION_ID=5
            - VANETZA_STATION_TYPE=5
            - VANETZA_MAC_ADDRESS=6e:06:e0:03:00:05
            - VANETZA_INTERFACE=br0
            - START_EMBEDDED_MOSQUITTO=true
            - SUPPORT_MAC_BLOCKING=true
            - VANETZA_CAM_PERIODICITY=0
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.22
        sysctls:
            kernel.msgmax: 16384
    obu4:
        hostname: obu4
        image: vanetza:test
        cap_add:
            - "NET_ADMIN"
        environment:
            - VANETZA_STATION_ID=6
            - VANETZA_STATION_TYPE=5
            - VANETZA_MAC_ADDRESS=6e:06:e0:03:00:06
            - VANETZA_INTERFACE=br0
            - START_EMBEDDED_MOSQUITTO=true
            - SUPPORT_MAC_BLOCKING=true
            - VANETZA_CAM_PERIODICITY=0
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.23
        sysctls:
            kernel.msgmax: 16384
    obu5:
        hostname: obu5
        image: vanetza:test
        cap_add:
            - "NET_ADMIN"
        environment:
            - VANETZA_STATION_ID=7
            - VANETZA_STATION_TYPE=5
            - VANETZA_MAC_ADDRESS=6e:06:e0:03:00:07
            - VANETZA_INTERFACE=br0
            - START_EMBEDDED_MOSQUITTO=true
            - SUPPORT_MAC_BLOCKING=true
            - VANETZA_CAM_PERIODICITY=0
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.24
        sysctls:
            kernel.msgmax: 16384

    obu6:
        hostname: obu6
        image: vanetza:test
        cap_add:
            - "NET_ADMIN"
        environment:
            - VANETZA_STATION_ID=8
            - VANETZA_STATION_TYPE=5
            - VANETZA_MAC_ADDRESS=6e:06:e0:03:00:08
            - VANETZA_INTERFACE=br0
            - START_EMBEDDED_MOSQUITTO=true
            - SUPPORT_MAC_BLOCKING=true
            - VANETZA_CAM_PERIODICITY=0
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.25
        sysctls:
            kernel.msgmax: 16384
    
    obu7:
        hostname: obu7
        image: vanetza:test
        cap_add:
            - "NET_ADMIN"
        environment:
            - VANETZA_STATION_ID=9
            - VANETZA_STATION_TYPE=5
            - VANETZA_MAC_ADDRESS=6e:06:e0:03:00:09
            - VANETZA_INTERFACE=br0
            - START_EMBEDDED_MOSQUITTO=true
            - SUPPORT_MAC_BLOCKING=true
            - VANETZA_CAM_PERIODICITY=0
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.26
        sysctls:
            kernel.msgmax: 16384
    
    obu8:
        hostname: obu8
        image: vanetza:test
        cap_add:
            - "NET_ADMIN"
        environment:
            - VANETZA_STATION_ID=10
            - VANETZA_STATION_TYPE=5
            - VANETZA_MAC_ADDRESS=6e:06:e0:03:00:10
            - VANETZA_INTERFACE=br0
            - START_EMBEDDED_MOSQUITTO=true
            - SUPPORT_MAC_BLOCKING=true
            - VANETZA_CAM_PERIODICITY=0
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.27
        sysctls:
            kernel.msgmax: 16384

networks:
    vanetzalan0:
        external: true
        name: vanetzalan0
